# Gradle daemon settings
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# Kotlin Multiplatform
kotlin.mpp.enableCInteropCommonization=true

# Compose Multiplatform
org.jetbrains.compose.experimental.uikit.enabled=true
